apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gw
  template:
    metadata:
      labels:
        app: api-gw
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: api-gw
          image: skillhub.azurecr.io/api-gw:latest
          ports:
            - containerPort: 4000
              name: api-gateway
      initContainers:
        - name: wait-for-rabbitmq
          image: kubectl
          command:
            - "/bin/sh"
            - "-c"
            - |
              until kubectl get pods -l app=rabbitmq -o jsonpath='{.items[*].status.phase}' | grep -q Running; do
               echo "Waiting for RabbitMQ pod to be ready..."
               sleep 2
              done
          resources:
            requests:
              cpu: 1m
              memory: 50Mi
            limits:
              cpu: 75m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gw
spec:
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
  selector:
    app: api-gw
