name: API GW CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths : 
      - "./apps/api"
  workflow_dispatch:

jobs:
  BuildPush:
    runs-on: ubuntu-latest
    env:
      APPNAME: "${{ env.APPNAME }}"
      ACRNAME: "${{ env.ACRNAME}}"
      RG: "${{ env.RG }}"
      ENVIRONMENT: "${{ env.ENVIRONMENT }}"
    steps:
      - name: Get application code from repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.APPREPO}}
          ref: ${{ env.APPREPOREF}}

      - name: Job parameter inspection
        run: |
          echo "RG is ${{ env.RG }}"
          echo "AKS name is ${{ env.AKSNAME }}"

      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Debugging
        run: |
          echo "Debugging"
          az acr list

      - name: ACR build
        id: acrbuild
        env:
          ACRSERVER: "${{ env.ACRNAME }}.azurecr.io"
          APPREPOPATH: "${{ env.APPREPOPATH}}"
          IMAGEREPO: "${{ env.APPNAME }}"
        run: |
          echo "Verifying directory contents in repo path $APPREPOPATH"
          ls $APPREPOPATH

          echo "Downcasing $ACRNAME for valid repository name"
          REPOSITORY=$(echo $ACRSERVER | tr '[:upper:]' '[:lower:]')

          echo "Requesting ACR build on $ACRNAME for image $IMAGEREPO:${{ github.sha }}"
          az acr build -t $REPOSITORY/$IMAGEREPO:${{ github.sha }} -r $ACRNAME $APPREPOPATH/.
  Deploy:
    runs-on: ubuntu-latest
    needs: [BuildPush]
    env:
      APPNAME: "${{ env.APPNAME }}"
      NAMESP: "${{ env.NAMESPACE }}"
      AKSNAME: "${{ env.AKSNAME}}"
      ACRNAME: "${{ env.ACRNAME}}"
      RG: "${{ env.RG }}"
      ENVIRONMENT: "${{ env.ENVIRONMENT }}"
    steps:
      - name: Get application k8s manifests from repo
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3.0
        with:
          version: "latest"

      - name: Set the target Azure Kubernetes Service (AKS) cluster.
        uses: azure/aks-set-context@v2.0
        with:
          cluster-name: ${{ env.AKSNAME }}
          resource-group: ${{ env.RG }}

      #aks-set-context doesn't do a kubelogin so we add it manually
      - name: Kubelogin
        env:
          kubeloginversion: "v0.0.11"
        run: |
          wget https://github.com/Azure/kubelogin/releases/download/${{ env.kubeloginversion }}/kubelogin-linux-amd64.zip
          unzip kubelogin-linux-amd64.zip
          sudo mv bin/linux_amd64/kubelogin /usr/bin
          kubelogin convert-kubeconfig -l azurecli

      - name: Deploy app to AKS
        uses: azure/k8s-deploy@v1.5
        env:
          ACRNAME: "${{ env.ACRNAME}}"
        with:
          manifests: |
            ./manifests/api-gw.yml
          images: |
            ${{ env.ACRNAME }}.azurecr.io/azure:${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}
          action: deploy
